default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: rails_blog

test:
  <<: *default
  database: your_app_name_test

production:
  <<: *default
  database: your_app_name_production
  username: your_production_postgres_username
  password: your_production_postgres_password